animateapp/urls.py
from django.urls import path

from animateapp import views
from animateapp.views import AnimateCreateView, AnimateDetailView

app_name = 'animateapp'

urlpatterns = [
    path('create/', AnimateCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AnimateDetailView.as_view(), name='detail')
]

djangoProject2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from animateapp.views import AnimateCreateView

urlpatterns = [
    path('', AnimateCreateView.as_view()),

    path('admin/', admin.site.urls),
    path('animates/', include('animateapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animateapp/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

# Create your models here.


class Animate(models.Model):
    #맨처음 이미지 저장
    image = models.ImageField(upload_to='ani_image/', null=True)
    #만화책 방향이 좌->우 인지 우->좌 인지 확인
    left_right_choice = (('좌', '좌->우'), ('우', '우->좌'))
    left_right = models.CharField(max_length=5, choices=left_right_choice, default='좌')
    #분리되고 영상제작후 영상 파일 저장(mp4형식)
    ani = models.FileField(upload_to='ani/',
                           validators=[FileExtensionValidator(
                               allowed_extensions=['avi', 'mp4', 'mkv', 'mpeg', 'webm'])],
                           null=True,
                           blank=True)
    #생성일자
    created_at = models.DateField(auto_now_add=True, null=True)

animateapp/forms.py
from django.forms import ModelForm, HiddenInput

from animateapp.models import Animate


class AnimateCreationForm(ModelForm):
    class Meta:
        model = Animate
        fields = ['image', 'ani', 'left_right']
        widgets = {
            #생성시 안보이게 처리
            'ani': HiddenInput(),
        }
        labels = {
            "left_right": "만화책 방향",
        }

        

animateapp/views.py
import datetime

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, DetailView

from animateapp.forms import AnimateCreationForm
from animateapp.models import Animate

from PIL import Image
import pytesseract
import cv2.cv2 as cv2
import os

#pytesseract 환경변수 지정후 위치 받아오는부분
#설정 해줘야 작동이 됨
pytesseract.pytesseract.tesseract_cmd = R'C:\Django\lib\Tesseract-OCR\tesseract'


class AnimateCreateView(CreateView):
    model = Animate
    form_class = AnimateCreationForm
    template_name = 'animateapp/create.html'

    def form_valid(self, form):
        #form 저장
        temp_upload = form.save(commit=False)
        temp_upload.save()
        temp_upload = form.save(commit=False)
        #이미지 저장된 위치 가져오기
        path = 'media/' + str(temp_upload.image)
        #좌우 만화책 방향 가져오기
        l_r = str(temp_upload.left_right)

        #crop(이미지 저장위치, 만화책방향)-임시로 이미지를 분할해서 글자수까지 나타내는함수
        #반환값은 cut의 [순서,이미지,글자수]의 리스트
        image_len_list = crop(path, l_r)

        #view_seconds(image_len_list)-cut의 순서 이미지 글자수를 가지고 영상화하는 함수
        #반환값은 영상 저장 위치
        video_path = view_seconds(image_len_list)

        #영상까지 form 저장
        temp_upload.ani = video_path
        temp_upload.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('animateapp:detail', kwargs={'pk': self.object.pk})


class AnimateDetailView(DetailView):
    model = Animate
    context_object_name = 'target_animate'
    template_name = 'animateapp/detail.html'


#임시로 이미지 분할
#앞으로 컷분리 모델이 들어갈 부분
def crop(path, l_r):
    #이미지 저장위치로 이미지 받아옮
    im = Image.open(path)
    #이미지 width, height 값 받아옮
    img_width, img_height = im.size

    #opencv 이미지 읽어오기
    src = cv2.imread(path, cv2.IMREAD_UNCHANGED)
    #이미지 3등분하기위한 높이값 나눔
    hei_3 = int(img_height / 3)
    #잘려진 cut과 순서 글자수를 넣을 리스트 미리생성
    crop_img = []
    # 이미지를 자른다.
    for i in range(3):
        #이미지를 [높이 나누는 부분: 넓이 전체]로 복사함
        dst = src[hei_3*i:hei_3*(i+1):, 0:img_width].copy()
        #img_text_len(dst)-잘려진cut으로 이미지로 글자수 측정 함수
        #반환값은 cut의 글자수
        txt_len = img_text_len(dst)
        #리스트에 순서, cut image, 글자수 추가
        crop_img.append([i, dst, txt_len])
    #cut의 [순서,이미지,글자수]의 리스트 반환
    return crop_img


#img_text_len(img)-이미지를 받아 글자수를 반환해주는 함수
def img_text_len(img):
    #pytesseract.image_to_string(이미지, 언어, 옵션)-tesseract의 ocr-이미지의 글자를 text형태로 반환
    out_text = pytesseract.image_to_string(img, lang='kor+eng', config='--psm 1 -c preserve_interword_spaces=1')
    #반환된 text의 줄바꿈과 앞,뒤 공백등을 제거
    out_text = out_text.replace("\n", "")
    out_text.strip()
    print("길이:" + str(len(out_text)))
    print(out_text)
    #글자수를 반환
    return len(out_text)


#[순서,이미지,글자수]의 리스트를 받아 영상으로 만들고 저장하는 함수
def view_seconds(image_list):
    #영상이름 오늘 날자와 시간으로 지정
    nowdate = datetime.datetime.now()
    daytime = nowdate.strftime("%Y-%m-%d_%H%M%S")
    #영상 저장 위치 설정
    video_name = 'ani/' + daytime + '.mp4'
    out_path = 'media/' + video_name
    #video codec 설정
    fourcc = cv2.VideoWriter_fourcc(*'H264')

    #현재 영상 프레임을 첫번째이미지로 설정(변경가능)
    frame = image_list[0][1]
    height, width, layers = frame.shape

    #video작성부분(저장위치, codec, fps, 영상프레임)
    video = cv2.VideoWriter(out_path, fourcc, 1.0, (width, height))
    #리스트에서 한 cut씩 가져옮
    for image in image_list:
        #기본 5초에 이미지의 글자수를 10으로 나눈만큼 반복하여 같은 이미지 기록
        each_image_duration = 5 + int(image[2]/10)
        for _ in range(each_image_duration):
            video.write(image[1])

    #객체를 반드시 종료시켜주어야 한다
    video.release()
    #모든 화면 종료해준다.
    cv2.destroyAllWindows()

    #영상 저장 위치 반환
    return video_name

animateapp/templates/animateapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h2>만화, 웹툰 영상화</h2>
        </div>
        <div>
            <form action="{% url 'animateapp:create' %}"
                  enctype="multipart/form-data"
                  method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal'%}

                <div class="m-5">
                    <input type="submit" class="btn btn-dark rounded-pill px-5">
                </div>

            </form>
        </div>
    </div>



{% endblock %}

animateapp/templates/animateapp/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container text-center">
        <div class="my-5">
            <video id="vid" width="530"  controls autoplay muted playsinline>
                <source src="{{ target_animate.ani.url }}" type="video/mp4">
                <object data="{{ target_animate.ani.url }}" width="320" height="240">
                <embed src="{{ target_animate.ani.url }}" width="320" height="240">
                </object>
            </video>
        </div>
        <div class="my-5">

            <a href="{{ target_animate.ani.url }}"
               class="btn btn-success rounded-pill px-5" download="video">
                다운로드
            </a>
            <a href="{% url 'animateapp:create' %}"
               class="btn btn-success rounded-pill px-5">
                처음으로
            </a>

        </div>

    </div>
    <script> document.getElementById('vid').play(); </script>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body style="font-family: NanumSquareB">

{% block content %}

{% endblock %}

</body>
</html>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>쿠키굽는 사람들</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    {#  GOOGLE PONTS LINK  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&family=Yomogi&display=swap" rel="stylesheet">

    {#  DEFAULT CSS LINK  #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# METERIAL ICON LINK #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


    {# 네이버 나눔스퀘어 글꼴 #}
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>


</head>